# Generated by Django 6.1.1 on 2026-09-21 13:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="copied from deal.offer_amount at calculation time",
                        max_digits=12,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="copied from deal.commission_rate",
                        max_digits=5,
                    ),
                ),
                (
                    "gross_commission",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="calculated: sale_price * commission_rate / 100",
                        max_digits=12,
                    ),
                ),
                (
                    "agent_split",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="percentage of gross commission going to the agent",
                        max_digits=5,
                    ),
                ),
                (
                    "agent_commission",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="calculated: gross_commission * agent_split / 100",
                        max_digits=12,
                    ),
                ),
                (
                    "brokerage_split",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="calculated: 100 - agent_split",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission",
                        to="deals.deal",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
