# Generated by Django 6.1.1 on 2026-09-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commission",
            options={"ordering": ["-created_at"]},
        ),
    ]
