# Generated by Django 6.1.1 on 2026-09-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-created_at"]},
        ),
    ]
