# Generated by Django 6.1.1 on 2026-09-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_options"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("interested", "Interested"),
                            ("viewing_scheduled", "Viewing scheduled"),
                            ("rejected", "Rejected"),
                            ("offer_made", "Offer made"),
                            ("purchased", "Purchased"),
                        ],
                        default="suggested",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_interests",
                        to="leads.lead",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interested_leads",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("lead", "property")},
            },
        ),
    ]
